# Set paths relative to this file so the problem set works from any current directory -
const _ROOT = @__DIR__;
const _PATH_TO_SRC = joinpath(_ROOT, "src");
const _PATH_TO_DATA = joinpath(_ROOT, "data");

# Load the standard-library tools used by the supplied support and test code -
using Statistics # summary statistics for the Advanced funding scenarios
using Test       # public tests for both tracks

# Load the complete support layer; students do not edit this file or Support.jl -
include(joinpath(_PATH_TO_SRC, "Support.jl"));
include(joinpath(_PATH_TO_SRC, "Sequences.jl")); # supplied strategy enumeration and cash-flow accounting
